import "dart:math";
import "package:flutter/services.dart";
import "package:flutter/widgets.dart";
import "package:nove/constants/domains/body_mass_index_calculator_constants.dart";
import "package:nove/constants/domains/time_aggregator_constants.dart";
import "package:nove/constants/domains/time_calculator_constants.dart";
import "package:nove/user_interface/internals/formatter/user_interface_formatter.dart";
import "package:nove/user_interface/internals/value_objects/device_language_strings_value_objects/concrete/english_strings_value_object.dart";
import "package:nove/user_interface/internals/value_objects/device_language_strings_value_objects/concrete/french_strings_value_object.dart";
import "package:nove/user_interface/internals/value_objects/theme_value_object/concrete/light_theme_value_object.dart";
import "package:nove/user_interface/internals/value_objects/widget_values_holder_value_objects/time_aggregator_input_controller_holder_value_object.dart";

final APPLICATION_LANGUAGE = EnglishStringsValueObject();

final NON_ENGLISH_LANGUAGE = FrenchStringsValueObject();

const CURRENT_CURRENCY_VALUES_KEY = "CURRENT_CURRENCY_VALUES";

const TEXT_INFORMATION_KEY = "TEXT_INFORMATION";

const TEXT_TO_BE_PARSED_KEY = "TEXT_TO_BE_PARSED";

const CANDIDATE_HEIGHT_KEY = "CANDIDATE_HEIGHT";

const CANDIDATE_WEIGHT_KEY = "CANDIDATE_WEIGHT";

const CALCULATED_BODY_MASS_INDEX_KEY = "CALCULATED_BODY_MASS_INDEX";

const PORTUGUESE_LANGUAGE_CODE = "pt";

const ENGLISH_LANGUAGE_CODE = "en";

const FRENCH_LANGUAGE_CODE = "fr";

const GERMAN_LANGUAGE_CODE = "de";

const ITALIAN_LANGUAGE_CODE = "it";

const SPANISH_LANGUAGE_CODE = "es";

const LIST_OF_PREVIOUS_EXPRESSION_SNAPSHOTS_KEY =
    "LIST_OF_PREVIOUS_EXPRESSION_SNAPSHOTS";

const LIST_OF_SPEED_UNITS_KEY = "LIST_OF_SPEED_UNITS";

const BASE_SPEED_UNIT_ELEMENT_INDEX_KEY = "BASE_SPEED_UNIT_ELEMENT_INDEX";

const BASE_AREA_UNIT_ELEMENT_INDEX_KEY = "BASE_AREA_UNIT_ELEMENT_INDEX";

const LIST_OF_AREA_UNITS_KEY = "LIST_OF_AREA_UNITS";

const BASE_TIME_UNIT_ELEMENT_INDEX_KEY = "BASE_TIME_UNIT_ELEMENT_INDEX";

const LIST_OF_TIME_UNITS_KEY = "LIST_OF_TIME_UNITS";

const BASE_LENGTH_UNIT_ELEMENT_INDEX_KEY = "BASE_LENGTH_UNIT_ELEMENT_INDEX";

const LIST_OF_LENGTH_UNITS_KEY = "LIST_OF_LENGTH_UNITS";

const BASE_MASS_UNIT_ELEMENT_INDEX_KEY = "BASE_MASS_UNIT_ELEMENT_INDEX";

const LIST_OF_MASS_UNITS_KEY = "LIST_OF_MASS_UNITS";

const BASE_TEMPERATURE_UNIT_ELEMENT_INDEX_KEY =
    "BASE_TEMPERATURE_UNIT_ELEMENT_INDEX";

const LIST_OF_TEMPERATURE_UNITS_KEY = "LIST_OF_TEMPERATURE_UNITS";

const BASE_NUMBER_SYSTEM_ELEMENT_INDEX_KEY = "BASE_NUMBER_SYSTEM_ELEMENT_INDEX";

const LIST_OF_NUMBER_SYSTEMS_KEY = "LIST_OF_NUMBER_SYSTEMS";

const CURRENT_EXPRESSION_SNAPSHOT_KEY = "EXPRESSION_SNAPSHOT";

const AGGREGATED_TIME_KEY = "AGGREGATED_TIME";

const LIST_OF_TIMES_KEY = "LIST_OF_TIMES";

const BASE_CURRENCY_UNIT_ELEMENT_INDEX_KEY = "BASE_CURRENCY_UNIT_ELEMENT_INDEX";

const LIST_OF_CURRENCY_UNITS_KEY = "LIST_OF_AREA_UNITS";

const FIRST_TIME_TO_BE_CALCULATED_KEY = "FIRST_TIME_TO_BE_CALCULATED";

const SECOND_TIME_TO_BE_CALCULATED_KEY = "SECOND_TIME_TO_BE_CALCULATED";

const CALCULATED_TIME_KEY = "CALCULATED_TIME";

const SNACKBAR_AUTOMATIC_DISMISS_DURATION = Duration(milliseconds: 3000);

const LIST_OF_ITEM_LENGTH = 2;

const LAST_ITEM_INDEX = LIST_OF_ITEM_LENGTH - 1;

const NOT_LAST_ITEM_INDEX = 0;

const DROPDOWN_MENU_WIDTH = 0.0;

const TIME_CYCLE_NUMBER_LENGTH = 2;

const TIME_CYCLE_HIGHEST_NUMBER = 59;

const TIME_HOUR_NUMBER_LENGTH = 4;

const AGGREGATOR_TIME_HOUR_NUMBER_LENGTH = 2;

const NON_NUMERIC_CHARACTER = "a";

const ZEROED_TIME_PLACEHOLDER = "00";

const ZEROED_HOUR_TIME_CYCLE_PLACEHOLDER = "0000";

TimeAggregatorInputControllerHolderValueObject
TIME_AGGREGATOR_INPUT_CONTROLLER_HOLDER() {
  return TimeAggregatorInputControllerHolderValueObject(
    TextEditingController(text: "${ZEROED_TIME.hours}"),
    TextEditingController(text: "${ZEROED_TIME.minutes}"),
    TextEditingController(text: "${ZEROED_TIME.seconds}"),
  );
}

final HOUR_INPUT_KEY = Key("HOUR_INPUT_KEY");

final MINUTE_INPUT_KEY = Key("MINUTE_INPUT_KEY");

final SECOND_INPUT_KEY = Key("SECOND_INPUT_KEY");

const LENGTH_OF_SYNCHRONIZED_LIST_OF_TIME_INPUT_CONTROLLER_HOLDERS = 2;

const LENGTH_OF_SYNCHRONIZED_LIST_OF_TIMES = 2;

const LENGTH_OF_SYNCHRONIZED_LIST_OF_MEASURE_UNITS_INPUT_CONTROLLER_HOLDERS = 2;

const LENGTH_OF_SYNCHRONIZED_LIST_OF_MEASURE_UNITS = 2;

const POINT_CHARACTER = ".";

const EXPONENTIAL_CHARACTER = "e";

const ANY_NON_NUMERICAL_OTHER_VALUE_POINT_CHARACTER = "A";

final NOT_ROUND_VALUE = "1.0";

const FIXED_SCREEN_SIZE = Size(2000, 2000);

const EXPRESSION_WITH_ALL_AVAILABLE_CHARACTERS = "1234567890+÷e!(*%π^^(-1))√";

const EXPRESSION_WITH_ALL_AVAILABLE_CHARACTERS_IN_NOT_SCIENTIFIC_KEYBOARD =
    "1234567890+÷!*^";

const SCIENTIFIC_KEYBOARD_MINIMAL_HEIGHT = 550.0;

const HORIZONTAL_KEYBOARD_MINIMAL_WIDTH = 450.0;

const NOT_SCIENTIFIC_CALCULATOR_KEYBOARD_SCREEN_SIZE = Size(300, 300);

const SCIENTIFIC_CALCULATOR_KEYBOARD_SCREEN_SIZE = Size(
  400,
  SCIENTIFIC_KEYBOARD_MINIMAL_HEIGHT + 100,
);

const HORIZONTAL_CALCULATOR_KEYBOARD_SCREEN_SIZE = Size(
  HORIZONTAL_KEYBOARD_MINIMAL_WIDTH + 100,
  400,
);

const LARGER_SCREEN_VIEWFINDER_HISTORY_CONTAINER_MINIMAL_HEIGHT_THRESHOLD =
    249.0;

const SMALL_SCREEN_VIEWFINDER_HISTORY_CONTAINER_MINIMAL_HEIGHT_THRESHOLD =
    190.0;

const SMALL_VIEWFINDER_HEIGHT = 600.0;

const NOT_ABLE_TO_BE_SHOWN_VIEWFINDER_SCREEN_HEIGHT = 600.0;

const NOT_ABLE_TO_BE_SHOWN_VIEWFINDER_SCREEN_WIDTH = 350.0;

const LARGE_SCREEN_UTILITY_BANNER_DECK_MINIMAL_WIDTH = 1000.0;

const MEDIUM_SCREEN_UTILITY_BANNER_DECK_MINIMAL_WIDTH = 750.0;

const LARGE_SCREEN_UTILITY_BANNER_DECK_SCREEN_SIZE = Size(
  LARGE_SCREEN_UTILITY_BANNER_DECK_MINIMAL_WIDTH + 100,
  400,
);

const MEDIUM_SCREEN_UTILITY_BANNER_DECK_SCREEN_SIZE = Size(
  MEDIUM_SCREEN_UTILITY_BANNER_DECK_MINIMAL_WIDTH + 100,
  400,
);

const SMALL_SCREEN_UTILITY_BANNER_DECK_SCREEN_SIZE = Size(
  MEDIUM_SCREEN_UTILITY_BANNER_DECK_MINIMAL_WIDTH,
  400,
);

const CALCULATOR_SCREEN_MINIMAL_HEIGHT = 575.0;

final APPLICATION_THEME = LightThemeValueObject();

final SCREEN_TO_BE_NAVIGATED = Container();

const HOME_SCREEN_KEY = Key("HOME_SCREEN");

final APPLICATION_HOME_SCREEN = Container(key: HOME_SCREEN_KEY);

const EXPRESSION_SNAPSHOT_ITEM_DISMISS_FULL_SWIPE = Offset(500, 0);

const UTILITY_BANNER_HEIGHT = 360.0;

const EXPRESSION_TO_BE_EVALUATED_SCROLL_OFFSET = 0.0;

const UTILITIES_PAGE_SWIPE = Offset(-500, 0);

const CALCULATOR_PAGE_SWIPE = Offset(500, 0);

final FOCUS_NODE = FocusNode();

final EXPRESSION_SNAPSHOT_ITEM_KEY = Key("EXPRESSION_SNAPSHOT_ITEM");

const SMALL_KEYBOARD_CHARACTER_HIGHEST_APPLICATION_WINDOW_HEIGHT = 670.0;

final HISTORY_NOT_ABLE_TO_BE_OPENED_SCREEN_HEIGHT = Size(500, 300);

const FOREGROUND_BACKDROP_POSITION = Offset(10, 10);

const OPENED_EXPRESSION_VIEWFINDER_HEIGHT = 488.0;

String CURRENCY_ITEM_DESCRIPTION(String currencyAbbreviation, double value) {
  return "$currencyAbbreviation | $value $currencyAbbreviation = USD";
}

final REMOVE_UNNECESSARY_ZEROS_FROM_VALUE_REGEX = RegExp(r"\.0$");

final REMOVE_UNNECESSARY_TRAILING_ZEROES_FROM_VALUE_REGULAR_EXPRESSION = RegExp(
  r"(\.\d*?)0+$",
);

final REMOVE_UNNECESSARY_TRAILING_DOTS_FROM_VALUE_REGULAR_EXPRESSION = RegExp(
  r"\.$",
);

const MAXIMUM_SCROLL_OFFSET = 100.0;

const TOOLTIP_SHOWING_DURATION = Duration(seconds: 1, milliseconds: 500);

const PORTRAIT_ORIENTATION = [DeviceOrientation.portraitUp];

const LANDSCAPE_ORIENTATION = [
  DeviceOrientation.portraitUp,
  DeviceOrientation.landscapeLeft,
  DeviceOrientation.landscapeRight,
];

const ANTE_MERIDIEM_PERIOD_OF_DAY_ACRONYMOUS = "AM";

const POST_MERIDIEM_PERIOD_OF_DAY_ACRONYMOUS = "PM";

const NOON_HOUR_OF_DAY = 12;

const DECIMAL_NUMBER_OF_DIGITS = 2;

const DECIMAL_NUMBER_PADDING = "0";

const UNPADDED_VALUE = "5";

const PADDED_VALUE = "05";

final RESOLVED_AGGREGATED_TIME_RESULT_PHRASE = APPLICATION_LANGUAGE
    .AGGREGATED_TIME_RESULT(
      UserInterfaceFormatter.getPaddedValue("${AGGREGATED_TIME.hours}"),
      UserInterfaceFormatter.getPaddedValue("${AGGREGATED_TIME.minutes}"),
      UserInterfaceFormatter.getPaddedValue("${AGGREGATED_TIME.seconds}"),
    );

final RESOLVED_CALCULATED_TIME_RESULT_PHRASE = APPLICATION_LANGUAGE
    .CALCULATED_TIME_RESULT(
      UserInterfaceFormatter.getPaddedValue("${CALCULATED_TIME.hours}"),
      UserInterfaceFormatter.getPaddedValue("${CALCULATED_TIME.minutes}"),
      UserInterfaceFormatter.getPaddedValue("${CALCULATED_TIME.seconds}"),
    );

final CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_ANTE_MERIDIEM_PERIOD_OF_DAY =
    DateTime(2026, 4, 19, 9, 30);

final CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_POST_MERIDIEM_PERIOD_OF_DAY =
    DateTime(2026, 4, 19, 21, 30);

final CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_TWENTY_FOUR_HOURS_FORMAT =
    DateTime(2026, 4, 19, 9, 30);

final RESOLVED_CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME_PHRASE_IN_ANTE_MERIDIEM_PERIOD_OF_DAY =
    APPLICATION_LANGUAGE.CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME(
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_ANTE_MERIDIEM_PERIOD_OF_DAY.hour}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_ANTE_MERIDIEM_PERIOD_OF_DAY.minute}",
      ),
      ANTE_MERIDIEM_PERIOD_OF_DAY_ACRONYMOUS,
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_ANTE_MERIDIEM_PERIOD_OF_DAY.month}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_ANTE_MERIDIEM_PERIOD_OF_DAY.day}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_ANTE_MERIDIEM_PERIOD_OF_DAY.year}",
      ),
    );

final RESOLVED_CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME_PHRASE_IN_POST_MERIDIEM_PERIOD_OF_DAY =
    APPLICATION_LANGUAGE.CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME(
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_POST_MERIDIEM_PERIOD_OF_DAY.hour - NOON_HOUR_OF_DAY}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_POST_MERIDIEM_PERIOD_OF_DAY.minute}",
      ),
      POST_MERIDIEM_PERIOD_OF_DAY_ACRONYMOUS,
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_POST_MERIDIEM_PERIOD_OF_DAY.month}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_POST_MERIDIEM_PERIOD_OF_DAY.day}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_POST_MERIDIEM_PERIOD_OF_DAY.year}",
      ),
    );

final RESOLVED_CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME_PHRASE_IN_TWENTY_FOUR_HOURS_FORMAT =
    NON_ENGLISH_LANGUAGE.CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME(
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_TWENTY_FOUR_HOURS_FORMAT.hour}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_TWENTY_FOUR_HOURS_FORMAT.minute}",
      ),
      POST_MERIDIEM_PERIOD_OF_DAY_ACRONYMOUS,
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_TWENTY_FOUR_HOURS_FORMAT.month}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_TWENTY_FOUR_HOURS_FORMAT.day}",
      ),
      UserInterfaceFormatter.getPaddedValue(
        "${CURRENT_CURRENCY_VALUES_UPDATED_AT_TIMESTAMP_IN_TWENTY_FOUR_HOURS_FORMAT.year}",
      ),
    );

final RESOLVED_UNDERWEIGHT_BODY_MASS_INDEX_RESULT_PHRASE = APPLICATION_LANGUAGE
    .BODY_MASS_INDEX_RESULT(
      UserInterfaceFormatter.getRoundNumberValue(
        "$UNDERWEIGHT_BODY_MASS_INDEX_VALUE",
      ),
      APPLICATION_LANGUAGE.UNDERWEIGHT_CATEGORY,
    );
final RESOLVED_NORMAL_BODY_MASS_INDEX_RESULT_PHRASE = APPLICATION_LANGUAGE
    .BODY_MASS_INDEX_RESULT(
      UserInterfaceFormatter.getRoundNumberValue(
        "$NORMAL_WEIGHT_BODY_MASS_INDEX_VALUE",
      ),
      APPLICATION_LANGUAGE.NORMAL_WEIGHT_CATEGORY,
    );
final RESOLVED_OVERWEIGHT_BODY_MASS_INDEX_RESULT_PHRASE = APPLICATION_LANGUAGE
    .BODY_MASS_INDEX_RESULT(
      UserInterfaceFormatter.getRoundNumberValue(
        "$OVERWEIGHT_BODY_MASS_INDEX_VALUE",
      ),
      APPLICATION_LANGUAGE.OVERWEIGHT_CATEGORY,
    );
final RESOLVED_OBESE_BODY_MASS_INDEX_RESULT_PHRASE = APPLICATION_LANGUAGE
    .BODY_MASS_INDEX_RESULT(
      UserInterfaceFormatter.getRoundNumberValue(
        "$OBESE_BODY_MASS_INDEX_VALUE",
      ),
      APPLICATION_LANGUAGE.OBESE_CATEGORY,
    );

const INDICATOR_BAR_ROTATION_ANGLE = 60 * pi / 180;

const ANOTHER_SCREEN = SizedBox.shrink();

const SCIENTIFIC_CALCULATOR_KEYBOARD_STATE_KEY =
    "SCIENTIFIC_CALCULATOR_KEYBOARD_STATE";

const STRING_OF_ITEM_TO_BE_STORED = "Stored Data";

const STORED_DATA_KEY = "STORED_DATA";

const STORED_DATA = "STORED_DATA";

const NOT_EXISTING_ITEM_ERROR_MESSAGE = "Item Does Not Exist!";

const CURRENT_APPLICATION_WINDOW_LARGER_SIDE = 500.0;

const CURRENT_APPLICATION_WINDOW_SMALLER_SIDE = 400.0;
