abstract class DeviceLanguageStringsValueObject {
  abstract final String NOT_VALID_EXPRESSION_ERROR_MESSAGE;

  abstract final String AREA_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String AREA_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String BODY_MASS_INDEX_CALCULATOR_UTILITY_NAME;

  abstract final String
  BODY_MASS_INDEX_CALCULATOR_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String CURRENCY_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String
  CURRENCY_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String MASS_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String MASS_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String NUMBER_SYSTEM_CONVERTER_UTILITY_NAME;

  abstract final String
  NUMBER_SYSTEM_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String SPEED_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String SPEED_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String TEMPERATURE_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String
  TEMPERATURE_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String TIME_AGGREGATOR_UTILITY_NAME;

  abstract final String TIME_AGGREGATOR_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String TIME_CALCULATOR_UTILITY_NAME;

  abstract final String TIME_CALCULATOR_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String TIME_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String TIME_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String LENGTH_UNIT_CONVERTER_UTILITY_NAME;

  abstract final String
  LENGTH_UNIT_CONVERTER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String TEXT_INFORMATION_PARSER_UTILITY_NAME;

  abstract final String
  TEXT_INFORMATION_PARSER_UTILITY_BANNER_ACCESSIBILITY_LABEL;

  abstract final String
  NAVIGATION_BAR_CALCULATOR_PAGE_ELEMENT_ACCESSIBILITY_LABEL;

  abstract final String
  NAVIGATION_BAR_UTILITIES_PAGE_ELEMENT_ACCESSIBILITY_LABEL;

  String SELECT_UNIT_ELEMENT_ACCESSIBILITY_LABEL(String unitName);

  String SELECT_UNIT_ELEMENT_TOOLTIP_MESSAGE(String unitName);

  abstract final String NAVIGATION_BAR_CALCULATOR_PAGE_TITLE;

  abstract final String NAVIGATION_BAR_UTILITIES_PAGE_TITLE;

  abstract final String ADD_UNIT_BUTTON_TOOLTIP_MESSAGE;

  abstract final String ADD_UNIT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String REMOVE_UNIT_BUTTON_TOOLTIP_MESSAGE;

  abstract final String REMOVE_UNIT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CURRENT_EXPRESSION_SNAPSHOT_RESULT_TITLE;

  abstract final String LIST_OF_PREVIOUS_EXPRESSION_SNAPSHOT_HISTORY_TITLE;

  String TEXT_INFORMATION_BREAKDOWN(String amountOfWords, String length);

  abstract final String BACK_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String RESET_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String TEXT_AREA_PLACEHOLDER;

  abstract final String TIME_HOUR_INPUT_TITLE;

  abstract final String TIME_MINUTE_INPUT_TITLE;

  abstract final String TIME_SECOND_INPUT_TITLE;

  String CALCULATED_TIME_RESULT(String hours, String minutes, String seconds);

  abstract final String ADD_BUTTON_TITLE;

  abstract final String SUBTRACT_BUTTON_TITLE;

  abstract final String ADD_TIME_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String SUBTRACT_TIME_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String WEIGHT_INPUT_TITLE;

  abstract final String HEIGHT_INPUT_TITLE;

  abstract final String AGE_INPUT_PLACEHOLDER;

  abstract final String WEIGHT_INPUT_PLACEHOLDER;

  abstract final String HEIGHT_INPUT_PLACEHOLDER;

  String BODY_MASS_INDEX_RESULT(String value, String category);

  abstract final String UNDERWEIGHT_CATEGORY;

  abstract final String NORMAL_WEIGHT_CATEGORY;

  abstract final String OVERWEIGHT_CATEGORY;

  abstract final String OBESE_CATEGORY;

  abstract final String CALCULATE_BUTTON_TITLE;

  abstract final String CALCULATE_BODY_MASS_INDEX_BUTTON_ACCESSIBILITY_LABEL;

  String CALCULATOR_CHARACTER_BUTTON_ACCESSIBILITY_LABEL(String character);

  abstract final String CALCULATOR_CLEAN_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_BACKSPACE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_EQUAL_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_EXPAND_KEYBOARD_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String LOADING_INDICATOR_ACCESSIBILITY_LABEL;

  abstract final String FOREGROUND_BACKDROP_ACCESSIBILITY_LABEL;

  abstract final String BACK_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESET_BUTTON_TOOLTIP_MESSAGE;

  abstract final String SELECT_BINARY_NUMBER_SYSTEM_DROPDOWN_ITEM_LABEL;

  abstract final String SELECT_BINARY_NUMBER_SYSTEM_DROPDOWN_ITEM_SHORTCUT;

  abstract final String
  SELECT_BINARY_NUMBER_SYSTEM_DROPDOWN_ITEM_ACCESSIBILITY_LABEL;

  abstract final String NUMBER_SYSTEM_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String
  CLEAN_LIST_OF_PREVIOUS_EXPRESSION_SNAPSHOT_HISTORY_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String EXPRESSION_SNAPSHOT_ITEM_ACCESSIBILITY_LABEL;

  abstract final String EXPAND_EXPRESSION_VIEWFINDER_BUTTON_TOOLTIP_MESSAGE;

  abstract final String EXPAND_EXPRESSION_VIEWFINDER_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String SHRINK_EXPRESSION_VIEWFINDER_BUTTON_TOOLTIP_MESSAGE;

  abstract final String SHRINK_EXPRESSION_VIEWFINDER_BUTTON_ACCESSIBILITY_LABEL;

  String AGGREGATED_TIME_RESULT(String hours, String minutes, String seconds);

  abstract final String ADD_TIME_NEXT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String ADD_TIME_NEXT_BUTTON_TOOLTIP_MESSAGE;

  abstract final String REMOVE_TIME_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String REMOVE_TIME_BUTTON_TOOLTIP_MESSAGE;

  abstract final String BASE_UNIT_LABEL;

  abstract final String ACRE_UNIT_LABEL;

  abstract final String ACRE_UNIT_ABBREVIATION;

  abstract final String HECTARE_UNIT_LABEL;

  abstract final String HECTARE_UNIT_ABBREVIATION;

  abstract final String SQUARE_CENTIMETER_UNIT_LABEL;

  abstract final String SQUARE_CENTIMETER_UNIT_ABBREVIATION;

  abstract final String SQUARE_FOOT_UNIT_LABEL;

  abstract final String SQUARE_FOOT_UNIT_ABBREVIATION;

  abstract final String SQUARE_INCH_UNIT_LABEL;

  abstract final String SQUARE_INCH_UNIT_ABBREVIATION;

  abstract final String SQUARE_KILOMETER_UNIT_LABEL;

  abstract final String SQUARE_KILOMETER_UNIT_ABBREVIATION;

  abstract final String SQUARE_METER_UNIT_LABEL;

  abstract final String SQUARE_METER_UNIT_ABBREVIATION;

  abstract final String SQUARE_MILE_UNIT_LABEL;

  abstract final String SQUARE_MILE_UNIT_ABBREVIATION;

  abstract final String SQUARE_MILLIMETER_UNIT_LABEL;

  abstract final String SQUARE_MILLIMETER_UNIT_ABBREVIATION;

  abstract final String SQUARE_YARD_UNIT_LABEL;

  abstract final String SQUARE_YARD_UNIT_ABBREVIATION;

  abstract final String AUSTRALIA_DOLLAR_UNIT_LABEL;

  abstract final String AUSTRALIA_DOLLAR_UNIT_ABBREVIATION;

  abstract final String BRAZIL_REAL_UNIT_LABEL;

  abstract final String BRAZIL_REAL_UNIT_ABBREVIATION;

  abstract final String CANADA_DOLLAR_UNIT_LABEL;

  abstract final String CANADA_DOLLAR_UNIT_ABBREVIATION;

  abstract final String EURO_UNIT_LABEL;

  abstract final String EURO_UNIT_ABBREVIATION;

  abstract final String UNITED_KINGDOM_POUND_UNIT_LABEL;

  abstract final String UNITED_KINGDOM_POUND_UNIT_ABBREVIATION;

  abstract final String NEW_ZEALAND_DOLLAR_UNIT_LABEL;

  abstract final String NEW_ZEALAND_DOLLAR_UNIT_ABBREVIATION;

  abstract final String SWITZERLAND_FRANC_UNIT_LABEL;

  abstract final String SWITZERLAND_FRANC_UNIT_ABBREVIATION;

  abstract final String UNITED_STATES_DOLLAR_UNIT_LABEL;

  abstract final String UNITED_STATES_DOLLAR_UNIT_ABBREVIATION;

  abstract final String CENTIMETER_UNIT_LABEL;

  abstract final String CENTIMETER_UNIT_ABBREVIATION;

  abstract final String FOOT_UNIT_LABEL;

  abstract final String FOOT_UNIT_ABBREVIATION;

  abstract final String INCH_UNIT_LABEL;

  abstract final String INCH_UNIT_ABBREVIATION;

  abstract final String KILOMETER_UNIT_LABEL;

  abstract final String KILOMETER_UNIT_ABBREVIATION;

  abstract final String METER_UNIT_LABEL;

  abstract final String METER_UNIT_ABBREVIATION;

  abstract final String MILE_UNIT_LABEL;

  abstract final String MILE_UNIT_ABBREVIATION;

  abstract final String MILLIMETER_UNIT_LABEL;

  abstract final String MILLIMETER_UNIT_ABBREVIATION;

  abstract final String NAUTICAL_MILE_UNIT_LABEL;

  abstract final String NAUTICAL_MILE_UNIT_ABBREVIATION;

  abstract final String YARD_UNIT_LABEL;

  abstract final String YARD_UNIT_ABBREVIATION;

  abstract final String GRAM_UNIT_LABEL;

  abstract final String GRAM_UNIT_ABBREVIATION;

  abstract final String KILOGRAM_UNIT_LABEL;

  abstract final String KILOGRAM_UNIT_ABBREVIATION;

  abstract final String MILLIGRAM_UNIT_LABEL;

  abstract final String MILLIGRAM_UNIT_ABBREVIATION;

  abstract final String OUNCE_UNIT_LABEL;

  abstract final String OUNCE_UNIT_ABBREVIATION;

  abstract final String POUND_UNIT_LABEL;

  abstract final String POUND_UNIT_ABBREVIATION;

  abstract final String TONNE_UNIT_LABEL;

  abstract final String TONNE_UNIT_ABBREVIATION;

  abstract final String BINARY_NUMBER_SYSTEM_LABEL;

  abstract final String BINARY_NUMBER_SYSTEM_ABBREVIATION;

  abstract final String OCTAL_NUMBER_SYSTEM_LABEL;

  abstract final String OCTAL_NUMBER_SYSTEM_ABBREVIATION;

  abstract final String DECIMAL_NUMBER_SYSTEM_LABEL;

  abstract final String DECIMAL_NUMBER_SYSTEM_ABBREVIATION;

  abstract final String HEXADECIMAL_NUMBER_SYSTEM_LABEL;

  abstract final String HEXADECIMAL_NUMBER_SYSTEM_ABBREVIATION;

  abstract final String FOOT_PER_SECOND_UNIT_LABEL;

  abstract final String FOOT_PER_SECOND_UNIT_ABBREVIATION;

  abstract final String INCH_PER_SECOND_UNIT_LABEL;

  abstract final String INCH_PER_SECOND_UNIT_ABBREVIATION;

  abstract final String METER_PER_SECOND_UNIT_LABEL;

  abstract final String METER_PER_SECOND_UNIT_ABBREVIATION;

  abstract final String KILOMETER_PER_SECOND_UNIT_LABEL;

  abstract final String KILOMETER_PER_SECOND_UNIT_ABBREVIATION;

  abstract final String KILOMETER_PER_HOUR_UNIT_LABEL;

  abstract final String KILOMETER_PER_HOUR_UNIT_ABBREVIATION;

  abstract final String MILE_PER_SECOND_UNIT_LABEL;

  abstract final String MILE_PER_SECOND_UNIT_ABBREVIATION;

  abstract final String MILE_PER_HOUR_UNIT_LABEL;

  abstract final String MILE_PER_HOUR_UNIT_ABBREVIATION;

  abstract final String KNOT_UNIT_LABEL;

  abstract final String KNOT_UNIT_ABBREVIATION;

  abstract final String MACH_UNIT_LABEL;

  abstract final String MACH_UNIT_ABBREVIATION;

  abstract final String LIGHTSPEED_UNIT_LABEL;

  abstract final String LIGHTSPEED_UNIT_ABBREVIATION;

  abstract final String CELSIUS_UNIT_LABEL;

  abstract final String CELSIUS_UNIT_ABBREVIATION;

  abstract final String FAHRENHEIT_UNIT_LABEL;

  abstract final String FAHRENHEIT_UNIT_ABBREVIATION;

  abstract final String KELVIN_UNIT_LABEL;

  abstract final String KELVIN_UNIT_ABBREVIATION;

  abstract final String MILLISECOND_UNIT_LABEL;

  abstract final String MILLISECOND_UNIT_ABBREVIATION;

  abstract final String SECOND_UNIT_LABEL;

  abstract final String SECOND_UNIT_ABBREVIATION;

  abstract final String MINUTE_UNIT_LABEL;

  abstract final String MINUTE_UNIT_ABBREVIATION;

  abstract final String HOUR_UNIT_LABEL;

  abstract final String HOUR_UNIT_ABBREVIATION;

  abstract final String DAY_UNIT_LABEL;

  abstract final String DAY_UNIT_ABBREVIATION;

  abstract final String WEEK_UNIT_LABEL;

  abstract final String WEEK_UNIT_ABBREVIATION;

  abstract final String YEAR_UNIT_LABEL;

  abstract final String YEAR_UNIT_ABBREVIATION;

  abstract final String AREA_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String CURRENCY_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String LENGTH_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String MASS_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String NUMBER_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String SPEED_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String TEMPERATURE_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String TIME_UNIT_DROPDOWN_MENU_ACCESSIBILITY_LABEL;

  abstract final String CONVERTER_INPUT_PLACEHOLDER;

  abstract final String RESTORE_DELETED_LIST_OF_PREVIOUS_EQUATIONS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_PREVIOUS_EQUATIONS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_PREVIOUS_EQUATIONS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_PREVIOUS_EQUATIONS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_TIME_CALCULATOR_DATA_MESSAGE;

  abstract final String RESTORE_DELETED_TIME_CALCULATOR_DATA_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_TIME_CALCULATOR_DATA_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_TIME_CALCULATOR_DATA_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_BODY_MASS_INDEX_CALCULATOR_DATA_MESSAGE;

  abstract final String
  RESTORE_DELETED_BODY_MASS_INDEX_CALCULATOR_DATA_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_BODY_MASS_INDEX_CALCULATOR_DATA_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_BODY_MASS_INDEX_CALCULATOR_DATA_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_AGGREGATED_TIMES_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_AGGREGATED_TIMES_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_AGGREGATED_TIMES_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_AGGREGATED_TIMES_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_AREA_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_AREA_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_AREA_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_AREA_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_TEXT_INFORMATION_DATA_MESSAGE;

  abstract final String RESTORE_DELETED_TEXT_INFORMATION_DATA_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_TEXT_INFORMATION_DATA_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_TEXT_INFORMATION_DATA_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_CURRENCY_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_CURRENCY_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_CURRENCY_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_CURRENCY_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_LENGTH_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_LENGTH_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_LENGTH_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_LENGTH_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_MASS_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_MASS_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_MASS_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_MASS_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_NUMBER_SYSTEM_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_NUMBER_SYSTEM_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_NUMBER_SYSTEM_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_NUMBER_SYSTEM_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_SPEED_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_SPEED_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_SPEED_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_SPEED_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_TEMPERATURE_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_TEMPERATURE_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_TEMPERATURE_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_TEMPERATURE_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_TIME_UNITS_MESSAGE;

  abstract final String RESTORE_DELETED_LIST_OF_TIME_UNITS_DESCRIPTION;

  abstract final String
  RESTORE_DELETED_LIST_OF_TIME_UNITS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String
  RESTORE_DELETED_LIST_OF_TIME_UNITS_BUTTON_TOOLTIP_MESSAGE;

  abstract final String
  CURRENT_CURRENCY_VALUES_RETRY_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CURRENT_CURRENCY_VALUES_RETRY_BUTTON_TOOLTIP_MESSAGE;

  abstract final String CURRENT_CURRENCY_VALUES_LAST_UPDATED_AT_DESCRIPTION;

  abstract final String CALCULATOR_ADD_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_SUBTRACT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_MULTIPLY_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_DIVIDE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_EQUALS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_CLEAR_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_POINT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_LEFT_PARENTHESIS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_RIGHT_PARENTHESIS_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_PERCENTAGE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_PI_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_E_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_ROOT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_POWER_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_FACTORIAL_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_RECIPROCAL_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_ZERO_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_ONE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_TWO_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_THREE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_FOUR_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_FIVE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_SIX_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_SEVEN_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_EIGHT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_NINE_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String CALCULATOR_SHRINK_KEYBOARD_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String ADD_UNIT_NEXT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String ADD_UNIT_NEXT_BUTTON_TOOLTIP_MESSAGE;

  abstract final String ADD_NUMBER_SYSTEM_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String ADD_NUMBER_SYSTEM_NEXT_BUTTON_ACCESSIBILITY_LABEL;

  abstract final String ADD_NUMBER_SYSTEM_NEXT_BUTTON_TOOLTIP_MESSAGE;

  String CURRENT_CURRENCY_VALUES_UPDATED_AT_TIME(
    String paddedCurrentHourOfDay,
    String currentMinuteOfDay,
    String periodOfTheDay,
    String currentMonthOfYear,
    String currentDayOfMonth,
    String currentYear,
  );
}
