platform :android do
  desc "Publishing application bundle to Google Play Store"
  lane :release do
    upload_to_play_store(
      track: "production",
      package_name: "org.tupi.nove",
      aab: "./build/app/outputs/bundle/release/app-release.aab",
      metadata_path: "./fastlane/metadata/android",
      json_key: "./fastlane/secrets/google-play-service-account.json",
      skip_upload_apk: true,
    )
  end
end
