const EXPRESSION_TO_BE_EVALUATED_WITHOUT_LAST_CHARACTER = "1+";

final REMOVE_UNNECESSARY_ZEROS_FROM_VALUE_REGEX = RegExp(r"\.0$");

final REMOVE_UNNECESSARY_TRAILING_ZEROES_FROM_VALUE_REGULAR_EXPRESSION = RegExp(
  r'(\.\d*?)0+$',
);

final VALUE_WITHOUT_UNNECESSARY_TRAILING_ZEROES_GROUP = 1;

final REMOVE_UNNECESSARY_TRAILING_DOTS_FROM_VALUE_REGULAR_EXPRESSION = RegExp(
  r'\.$',
);

const EXPRESSION_VALUE_FLOATING_POINT_FIXED_TRUNCATION_LENGTH = 4;

const NOT_FIXED_POINT_VALUE = "1.23456789";

const FIXED_POINT_VALUE = "1.2346";
