const NOT_VALID_EXPRESSION_ERROR_MESSAGE = "Expression Is Not Valid!";

final SQUARE_ROOT_SYMBOL_FINDING_REGULAR_EXPRESSION = RegExp(r"√([^)]+)");

final EULER_CONSTANT_SYMBOL_FINDING_REGULAR_EXPRESSION = RegExp(r"\be\b");

final PI_CONSTANT_SYMBOL_FINDING_REGULAR_EXPRESSION = RegExp(r"π");

const VALID_PI_CONSTANT_SYMBOL = "3.141592653589793238";

const VALID_EULER_CONSTANT_SYMBOL = "2.718281828459045235";

const SQUARE_ROOT_RADICAL_GROUP = 1;

String VALID_SQUARE_ROOT_SYMBOL(String radicandNumber) {
  return "sqrt($radicandNumber)";
}

const VALID_PERCENTAGE_SYMBOL = "/100";

const NOT_FORMATTED_EXPRESSION = "√eπ%÷";

const FORMATTED_EXPRESSION =
    "sqrt(2.718281828459045235*3.141592653589793238/100/)";

final SPACE_BETWEEN_TWO_LETTER_CHARACTERS_FINDING_REGULAR_EXPRESSION = RegExp(
  r"(?<=[eπ])(?=[eπ])",
);

final PERCENTAGE_SYMBOL_FINDING_REGULAR_EXPRESSION = RegExp(r"%");

const EXPRESSION_TO_BE_EVALUATED = "1+1";

const NOT_VALID_EXPRESSION = "1++";

const EVALUATED_EXPRESSION = 2;

const NOT_ROUND_EVALUATED_EXPRESSION = 2.1;

const MULTIPLY_SYMBOL = "*";

const VALID_DIVIDE_SYMBOL = "/";

final DIVIDE_SYMBOL_FINDING_REGULAR_EXPRESSION = RegExp(r"÷");

const EXPRESSION_WITH_UNNECESSARY_ZEROS = "1.1000";

const EXPRESSION_WITHOUT_UNNECESSARY_ZEROS = "1.1";
