import "package:nove/domain/mass_unit_converter/internals/test_utilities/test_mass_unit_entity.dart";
import "package:nove/domain/mass_unit_converter/mass_unit.dart";
import "package:nove/domain/mass_unit_converter/kilogram_unit_entity.dart";
import "package:nove/domain/mass_unit_converter/mass_unit_entity.dart";
import "package:nove/domain/measure_unit_converter/measure_unit_entity.dart";

const MASS_UNIT_VALUE = "1";

const INITIAL_MASS_UNIT_VALUE = "0";

const ZEROED_MASS_UNIT_VALUE = "0";

TestMassUnitEntity MASS_UNIT_TO_CONVERT_TO(
  Function(MeasureUnitEntity<MassUnit> measureUnit) convertToImplementation,
) {
  return TestMassUnitEntity(
    MASS_UNIT_VALUE,
    MassUnit.KILOGRAM,
    convertToImplementation,
  );
}

TestMassUnitEntity UPDATED_MASS_UNIT(
  Function(MeasureUnitEntity<MassUnit> measureUnit) convertToImplementation,
) {
  return TestMassUnitEntity(
    MASS_UNIT_VALUE + MASS_UNIT_VALUE,
    MassUnit.KILOGRAM,
    convertToImplementation,
  );
}

final ZEROED_MASS_UNIT = KilogramUnitEntity(ZEROED_MASS_UNIT_VALUE);

MassUnitEntity RESET_MASS_UNIT() {
  return KilogramUnitEntity(ZEROED_MASS_UNIT_VALUE);
}

const KILOGRAM_IN_TONNE_CONVERSION_MULTIPLIER = 0.001;

const GRAM_IN_TONNE_CONVERSION_MULTIPLIER = 0.000001;

const MILLIGRAM_IN_TONNE_CONVERSION_MULTIPLIER = 0.000000001;

const POUND_IN_TONNE_CONVERSION_MULTIPLIER = 0.000453592;

const OUNCE_IN_TONNE_CONVERSION_MULTIPLIER = 0.000028349523125;

const TONNE_IN_KILOGRAM_CONVERSION_MULTIPLIER = 1000.0;

const GRAM_IN_KILOGRAM_CONVERSION_MULTIPLIER = 0.001;

const MILLIGRAM_IN_KILOGRAM_CONVERSION_MULTIPLIER = 0.000001;

const POUND_IN_KILOGRAM_CONVERSION_MULTIPLIER = 0.45359237;

const OUNCE_IN_KILOGRAM_CONVERSION_MULTIPLIER = 0.028349523125;

const TONNE_IN_GRAM_CONVERSION_MULTIPLIER = 1000000.0;

const KILOGRAM_IN_GRAM_CONVERSION_MULTIPLIER = 1000.0;

const MILLIGRAM_IN_GRAM_CONVERSION_MULTIPLIER = 0.001;

const POUND_IN_GRAM_CONVERSION_MULTIPLIER = 453.59237;

const OUNCE_IN_GRAM_CONVERSION_MULTIPLIER = 28.349523125;

const TONNE_IN_MILLIGRAM_CONVERSION_MULTIPLIER = 1000000000.0;

const KILOGRAM_IN_MILLIGRAM_CONVERSION_MULTIPLIER = 1000000.0;

const GRAM_IN_MILLIGRAM_CONVERSION_MULTIPLIER = 1000.0;

const POUND_IN_MILLIGRAM_CONVERSION_MULTIPLIER = 453592.37;

const OUNCE_IN_MILLIGRAM_CONVERSION_MULTIPLIER = 28349.523125;

const TONNE_IN_POUND_CONVERSION_MULTIPLIER = 2204.62262185;

const KILOGRAM_IN_POUND_CONVERSION_MULTIPLIER = 2.20462262185;

const GRAM_IN_POUND_CONVERSION_MULTIPLIER = 0.002204622621848776;

const MILLIGRAM_IN_POUND_CONVERSION_MULTIPLIER = 2.2046226218487758e-8;

const OUNCE_IN_POUND_CONVERSION_MULTIPLIER = 0.0625;

const TONNE_IN_OUNCE_CONVERSION_MULTIPLIER = 35273.9619496;

const KILOGRAM_IN_OUNCE_CONVERSION_MULTIPLIER = 35.2739619496;

const GRAM_IN_OUNCE_CONVERSION_MULTIPLIER = 0.035273961949580414;

const MILLIGRAM_IN_OUNCE_CONVERSION_MULTIPLIER = 3.527396194958041e-11;

const POUND_IN_OUNCE_CONVERSION_MULTIPLIER = 16.0;

final MARSHALLED_MASS_UNIT =
    "{\"measureUnit\":\"${MassUnit.KILOGRAM.name}\",\"value\":\"$INITIAL_MASS_UNIT_VALUE\"}";

final MARSHALLED_LIST_OF_MASS_UNIT = "[$MARSHALLED_MASS_UNIT]";
