import "package:nove/domain/measure_unit_converter/measure_unit_entity.dart";
import "package:nove/domain/speed_unit_converter/internals/test_utilities/test_speed_unit_entity.dart";
import "package:nove/domain/speed_unit_converter/speed_unit.dart";
import "package:nove/domain/speed_unit_converter/kilometer_per_hour_unit_entity.dart";
import "package:nove/domain/speed_unit_converter/speed_unit_entity.dart";

const SPEED_UNIT_VALUE = "1";

const ZEROED_SPEED_UNIT_VALUE = "0";

TestSpeedUnitEntity SPEED_UNIT_TO_CONVERT_TO(
  Function(MeasureUnitEntity<SpeedUnit> measureUnit) convertToImplementation,
) {
  return TestSpeedUnitEntity(
    SPEED_UNIT_VALUE,
    SpeedUnit.KILOMETER_PER_HOUR,
    convertToImplementation,
  );
}

TestSpeedUnitEntity UPDATED_SPEED_UNIT(
  Function(MeasureUnitEntity<SpeedUnit> measureUnit) convertToImplementation,
) {
  return TestSpeedUnitEntity(
    SPEED_UNIT_VALUE + SPEED_UNIT_VALUE,
    SpeedUnit.KILOMETER_PER_HOUR,
    convertToImplementation,
  );
}

final ZEROED_SPEED_UNIT = KilometerPerHourUnitEntity(ZEROED_SPEED_UNIT_VALUE);

SpeedUnitEntity RESET_SPEED_UNIT() {
  return KilometerPerHourUnitEntity(ZEROED_SPEED_UNIT_VALUE);
}

const FOOT_PER_SECOND_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 0.3048;

const INCH_PER_SECOND_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 0.0254;

const KILOMETER_PER_SECOND_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 1000.0;

const KILOMETER_PER_HOUR_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER =
    0.2777777778;

const MILE_PER_SECOND_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 1609.344;

const MILE_PER_HOUR_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 0.44704;

const KNOT_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 0.514444;

const MACH_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 343.0;

const LIGHTSPEED_IN_METER_PER_SECOND_CONVERSION_MULTIPLIER = 299792458.0;

const METER_PER_SECOND_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 3.28084;

const INCH_PER_SECOND_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER =
    0.08333333333333333;

const KILOMETER_PER_SECOND_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 3280.84;

const KILOMETER_PER_HOUR_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 0.911344;

const MILE_PER_SECOND_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 5280.0;

const MILE_PER_HOUR_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 1.4666666667;

const KNOT_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 1.68781;

const MACH_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 1125.33;

const LIGHTSPEED_IN_FOOT_PER_SECOND_CONVERSION_MULTIPLIER = 983571056.43;

const METER_PER_SECOND_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 39.37007874;

const FOOT_PER_SECOND_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 12.0;

const KILOMETER_PER_SECOND_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER =
    39370.07874;

const KILOMETER_PER_HOUR_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 10.9361;

const MILE_PER_SECOND_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 63360.0;

const MILE_PER_HOUR_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 17.6;

const KNOT_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 20.2537;

const MACH_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 13500.0;

const LIGHTSPEED_IN_INCH_PER_SECOND_CONVERSION_MULTIPLIER = 111803149528.0;

const METER_PER_SECOND_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 3.6;

const FOOT_PER_SECOND_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 1.09728;

const INCH_PER_SECOND_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 0.09144;

const KILOMETER_PER_SECOND_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 3600.0;

const MILE_PER_HOUR_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 1.609344;

const MILE_PER_SECOND_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 5793.6384;

const KNOT_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 1.852;

const MACH_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 1234.8;

const LIGHTSPEED_IN_KILOMETER_PER_HOUR_CONVERSION_MULTIPLIER = 1079252848.8;

const METER_PER_SECOND_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER = 0.001;

const FOOT_PER_SECOND_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER =
    0.0003047999902464003;

const INCH_PER_SECOND_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER =
    0.0000254000000001016;

const KILOMETER_PER_HOUR_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER =
    0.0002777777778;

const MILE_PER_SECOND_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER = 1.609344;

const MILE_PER_HOUR_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER = 0.00044704;

const KNOT_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER = 0.00051440329218107;

const MACH_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER = 0.343;

const LIGHTSPEED_IN_KILOMETER_PER_SECOND_CONVERSION_MULTIPLIER = 299792.458;

const METER_PER_SECOND_IN_KNOT_CONVERSION_MULTIPLIER = 1.943844;

const FOOT_PER_SECOND_IN_KNOT_CONVERSION_MULTIPLIER = 0.5924837511331251;

const INCH_PER_SECOND_IN_KNOT_CONVERSION_MULTIPLIER = 0.04937369468294682;

const KILOMETER_PER_HOUR_IN_KNOT_CONVERSION_MULTIPLIER = 0.5399568;

const KILOMETER_PER_SECOND_IN_KNOT_CONVERSION_MULTIPLIER = 1943.844;

const MILE_PER_HOUR_IN_KNOT_CONVERSION_MULTIPLIER = 0.868976;

const MILE_PER_SECOND_IN_KNOT_CONVERSION_MULTIPLIER = 3128.314;

const MACH_IN_KNOT_CONVERSION_MULTIPLIER = 666.74;

const LIGHTSPEED_IN_KNOT_CONVERSION_MULTIPLIER = 582749918.284;

const METER_PER_SECOND_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 2.2369362921;

const FOOT_PER_SECOND_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 0.6818181818;

const INCH_PER_SECOND_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 0.0568181818;

const KILOMETER_PER_HOUR_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 0.621371;

const KILOMETER_PER_SECOND_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER =
    2236.9362921;

const MILE_PER_SECOND_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 3600.0;

const KNOT_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 1.150779;

const MACH_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 767.269;

const LIGHTSPEED_IN_MILE_PER_HOUR_CONVERSION_MULTIPLIER = 670616629.384;

const METER_PER_SECOND_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 1609.344;

const FOOT_PER_SECOND_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 5280.0;

const INCH_PER_SECOND_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 63360.0;

const KILOMETER_PER_SECOND_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 1.609344;

const KILOMETER_PER_HOUR_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 0.000172603;

const MILE_PER_HOUR_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 0.0002777777778;

const KNOT_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 0.868976;

const MACH_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 4.69288;

const LIGHTSPEED_IN_MILE_PER_SECOND_CONVERSION_MULTIPLIER = 186282.397;

const METER_PER_SECOND_IN_MACH_CONVERSION_MULTIPLIER = 0.002938669957;

const FOOT_PER_SECOND_IN_MACH_CONVERSION_MULTIPLIER = 0.000895191;

const INCH_PER_SECOND_IN_MACH_CONVERSION_MULTIPLIER = 0.000074599;

const KILOMETER_PER_SECOND_IN_MACH_CONVERSION_MULTIPLIER = 2.938669957;

const KILOMETER_PER_HOUR_IN_MACH_CONVERSION_MULTIPLIER = 0.00081;

const MILE_PER_SECOND_IN_MACH_CONVERSION_MULTIPLIER = 0.21313;

const MILE_PER_HOUR_IN_MACH_CONVERSION_MULTIPLIER = 0.001303;

const KNOT_IN_MACH_CONVERSION_MULTIPLIER = 0.001512;

const LIGHTSPEED_IN_MACH_CONVERSION_MULTIPLIER = 874000.0;

const METER_PER_SECOND_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 0.00000000334;

const FOOT_PER_SECOND_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 1.016702651e-9;

const INCH_PER_SECOND_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 8.47252209e-11;

const KILOMETER_PER_SECOND_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 1.716e-9;

const KILOMETER_PER_HOUR_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 0.000000000926;

const MILE_PER_SECOND_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 5.3681912e-6;

const MILE_PER_HOUR_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 1.49116e-9;

const KNOT_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 1.716e-9;

const MACH_IN_LIGHTSPEED_CONVERSION_MULTIPLIER = 1.14473e-6;

final MARSHALLED_SPEED_UNIT =
    "{\"measureUnit\":\"${SpeedUnit.KILOMETER_PER_HOUR.name}\",\"value\":\"$ZEROED_SPEED_UNIT_VALUE\"}";

final MARSHALLED_LIST_OF_SPEED_UNIT = "[$MARSHALLED_SPEED_UNIT]";
